### ISSUE TITLE
ak and bk setting

### ISSUE THREAD

**Issue by AI-rcl** [parthnakar1/SOC-Estimation-using-Kalman-Filter#1]
hello, thank you for  your sharing,  but  I have a question to ask you.  the  ak = [[0.9757691089747373,0],[0,1]]  and  the   bk = [[-0.006784883474301327,0],[0,0]], I want to known why you set them  like this ,  experience ? , thank you

**Comment by parthnakar1** [comment]
The ak and bk matrices depend on cell model selected.
![image](https://user-images.githubusercontent.com/56785540/120643076-53cb4880-c493-11eb-81fb-2e2358eba598.png)
(image of model attached)
𐤃t = time difference between 2 data points
τ = time constant for diffusion voltage (=R1*C1)
Qtotal = total cell capacity
Here, Vcapacitor(t) = Vcapacitor(t-1) * e^(-𐤃t/τ)  +  I(t-1) * (1 - e^(-𐤃t/τ)) * R1
and   SOC(t) = SOC(t-1) - I(t-1)*𐤃t/Qtotal
(further kalman filtering is used on this model)
These equations are then converted to linear algebra problem where ak and bk are coefficient matrices for state variables X and input variable U.
They are initialized based on above equations and calculated before each new iteration.

**Comment by AI-rcl** [comment]
thank you for your sharing ,It helps me a lot
